### ISSUE TITLE
T2I inference code fails to load light lora

### ISSUE THREAD

**Issue by dibbla** [MFaceTech/HyperDreamBooth#2]
Hi @chenxinhua!

Thanks for open-sourcing this great work and providing great insights into implementing HyperDB.

I am working with the first step, which is training LightLoRA and it seems like the LoRA loading fails in `T2I_inference.py`. The error message is:
```
KeyError: 'lora.down.weight'
``` 
I believe this is due to the key mismatch issue as we don't have such key in light LoRA layers. Do you have some alternative approaches to test the light LoRA trained? I am working with diffusers=0.24,, is it the same version as you work with?

Thanks! 😄

**Comment by dibbla** [comment]
The liloras saved during training are not converted to standard lora. It should be fine to use the final lilora saved, which has been converted to standard lora.

Closing as issue resolved.

**Comment by chenxinhua** [comment]
It might be an issue caused by the update of the diffuser version.
